language: node_js
node_js:
  - "6"
  
env:
  matrix:
    # parallelize tests
    - INSTALLER=yarn PROJECT_URL=https://github.com/facebook/react.git
    - INSTALLER=npm PROJECT_URL=https://github.com/facebook/react.git

install:
  - if [ "$INSTALLER" = "yarn" ]; then npm install -g yarn; fi
  
before_script:
  - chmod +x *.sh

script:
  - git clone $PROJECT_URL
  - ./$INSTALLER.sh
