language: node_js
node_js:
  - "6"

env:
  matrix:
    # react
    - INSTALLER=yarn INSTALLER_VERSION=stable NAME=react REPO=https://github.com/facebook/react.git
    - INSTALLER=yarn INSTALLER_VERSION=next   NAME=react REPO=https://github.com/facebook/react.git
    - INSTALLER=npm  INSTALLER_VERSION=stable NAME=react REPO=https://github.com/facebook/react.git
    - INSTALLER=npm  INSTALLER_VERSION=next   NAME=react REPO=https://github.com/facebook/react.git

    # ghost
    - INSTALLER=yarn INSTALLER_VERSION=stable NAME=ghost REPO=https://github.com/TryGhost/Ghost.git
    - INSTALLER=yarn INSTALLER_VERSION=next   NAME=ghost REPO=https://github.com/TryGhost/Ghost.git
    - INSTALLER=npm  INSTALLER_VERSION=stable NAME=ghost REPO=https://github.com/TryGhost/Ghost.git
    - INSTALLER=npm  INSTALLER_VERSION=next   NAME=ghost REPO=https://github.com/TryGhost/Ghost.git

install:
  - if [[ $INSTALLER == "yarn" ]] && [[ $INSTALLER_VERSION == "stable" ]]; then npm install -g yarn; fi
  - if [[ $INSTALLER == "yarn" ]] && [[ $INSTALLER_VERSION == "next" ]]; then   npm install -g yarn@rc; fi
  - if [[ $INSTALLER == "npm" ]]  && [[ $INSTALLER_VERSION == "stable" ]]; then npm install -g npm; fi
  - if [[ $INSTALLER == "npm" ]]  && [[ $INSTALLER_VERSION == "next" ]]; then   npm install -g npm@next; fi

before_script:
  - chmod +x *.sh

script:
  - export GOOGLE_OAUTH_TOKEN=$(curl --request POST --url https://www.googleapis.com/oauth2/v3/token -d "client_secret=$GOOGLE_OAUTH_CLIENT_SECRET&grant_type=refresh_token&refresh_token=$GOOGLE_OAUTH_REFRESH_TOKEN&client_id=$GOOGLE_OAUTH_CLIENT_ID" | jq -r '.access_token')
  - ./$INSTALLER.sh $NAME $REPO
