language: node_js
node_js:
  - "6"

env:
  matrix:
    # parallelize tests
    - INSTALLER=yarn INSTALLER_VERSION=stable
    - INSTALLER=yarn INSTALLER_VERSION=next
    - INSTALLER=npm INSTALLER_VERSION=stable
    - INSTALLER=npm INSTALLER_VERSION=next

install:
  - if [[ $INSTALLER == "yarn" ]] && [[ $INSTALLER_VERSION == "stable" ]]; then npm install -g yarn; fi
  - if [[ $INSTALLER == "yarn" ]] && [[ $INSTALLER_VERSION == "next" ]]; then npm install -g yarn@rc; fi
  - if [[ $INSTALLER == "npm" ]] && [[ $INSTALLER_VERSION == "next" ]]; then npm install -g npm@next; fi

before_script:
  - chmod +x *.sh

script:
  - ./$INSTALLER.sh https://github.com/facebook/react.git
  - ./$INSTALLER.sh https://github.com/TryGhost/Ghost.git
