language: node_js
node_js:
  - "6"

env:
  matrix:
    # parallelize tests
    - INSTALLER=yarn INSTALLER_VERSION=stable PROJECT_URL=https://github.com/facebook/react.git
    #- INSTALLER=yarn INSTALLER_VERSION=next PROJECT_URL=https://github.com/facebook/react.git
    - INSTALLER=npm INSTALLER_VERSION=stable PROJECT_URL=https://github.com/facebook/react.git
    #- INSTALLER=npm INSTALLER_VERSION=next PROJECT_URL=https://github.com/facebook/react.git

install:
  - if [ "$INSTALLER" = "yarn" && "INSTALLER_VERSION" = "stable" ]; then npm install -g yarn; fi
  - if [ "$INSTALLER" = "yarn" && "INSTALLER_VERSION" = "next" ]; then npm install -g yarn; fi
  - if [ "$INSTALLER" = "npm" && "INSTALLER_VERSION" = "next" ]; then npm install -g npm; fi

before_script:
  - chmod +x *.sh

script:
  - git clone $PROJECT_URL
  - ./$INSTALLER.sh
